# Generated by Django 3.0 on 2019-12-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Just for migration'),
            preserve_default=False,
        ),
    ]
